I = imread('inputSeamCarvingPrague.jpg');
I1 = rgb2gray(I);
energyMap = imfilter(I1, fspecial('laplacian'));  
figure;
imagesc(energyMap);
title('EnergyMapFilteredPrague');
pause;
saveas(1, 'EnergyMapFilteredPrague','png');
CumulativeMap = cumulative_energy_map(energyMap,"HORIZONTAL");
CumulativeMap2 = cumulative_energy_map(energyMap,"VERTICAL");
figure;
imagesc(CumulativeMap);
title('Horizontal Cumulative Energy Map');
pause;
saveas(2, 'CumulativeEnergyFilteredHorizontalPrague','png');
figure;
imagesc(CumulativeMap2);
title('Vertical Cumulative Energy Map');
pause;
saveas(3, 'CumulativeEnergyFilteredVerticalPrague','png');

p = find_Vertical_Seam(CumulativeMap2);
q = find_horizontal_Seam(CumulativeMap);
figure;
imshow(I1);
hold on;
view_seam(I1,p,"VERTICAL");
hold on;
view_seam(I1,q,"HORIZONTAL");
pause;
saveas(4,'VerticalAndHorizontalSeamFiltered','png');